gt_u7_gps_node:
  ros__parameters:
    port: "/dev/ttyS0"
    baud_rate: 115200
    nmea_rates: 5
    frame_id: "gps"
    publish_hz: 5.0
    mode: "GPS_GLO_5HZ"  # "GPS_10HZ" or "GPS_GLO_5HZ"
    uere_m: 5.0
    min_sigma_xy: 1.0
    min_sigma_z: 2.0
    vertical_scale: 2.0

