ekf_localization_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    print_diagnostics: true

    # Frames (standard)
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # IMU: use only wz (yaw rate)
    imu0: /vehicle/imu/data
    imu0_config: [false,false,false,  false,false,false,  false,false,false,  false,false,true,  false,false,false]
    imu0_queue_size: 20

    # Wheel speed -> body vx
    twist0: /vehicle/velocity
    odom0: /wheel/odometry
    odom0_config: [
    false, false, false,  # x, y, z
    false, false, false,  # roll, pitch, yaw
    true,  false, false,  # vx, vy, vz
    false, false, true,   # vroll, vpitch, vyaw
    false, false, false   # ax, ay, az
  ]
    odom0_queue_size: 20

    # GPS pose (from navsat)
    pose0: /filtered/gps/pose
    pose0_config: [true,true,false,  false,false,false,  false,false,false,  false,false,false]
    pose0_queue_size: 10
    pose0_rejection_threshold: 3.5

    # Light process noise to start (tune later)
    #process_noise_covariance: [0.05, 0.0, 0.0,   0.0, 0.05, 0.0,   0.0,0.0,0.02,   0.0,0.0,0.0,   0.0,0.0,0.0,   0.0,0.0,0.0]
